# shellcheck shell=bash

SOVIEZ_ERR_MIGRATION=25

SOVIEZ_MIG_OP_DISCOVERY=migration_source_discovery
SOVIEZ_MIG_OP_BOOTSTRAP=migration_destination_bootstrap
SOVIEZ_MIG_OP_PAIRING=migration_trust_pairing
SOVIEZ_MIG_OP_READINESS=migration_readiness_assessment
SOVIEZ_MIG_OP_ABORT=migration_pair_abort
SOVIEZ_MIG_OP_DOMAIN_PLAN=migration_domain_plan
SOVIEZ_MIG_OP_DNS_CHALLENGE=migration_dns_challenge
SOVIEZ_MIG_OP_LANDING=migration_landing_prepare
SOVIEZ_MIG_OP_TLS=migration_tls_prepare
SOVIEZ_MIG_OP_ROUTING=migration_routing_readiness
SOVIEZ_MIG_OP_DOMAIN_ABORT=migration_domain_abort

# Phase 19 operation types
SOVIEZ_MIG_OP_TRANSFER_PLAN=migration_transfer_plan
SOVIEZ_MIG_OP_PAYLOAD_PRESYNC=migration_payload_presync
SOVIEZ_MIG_OP_DATABASE_TRANSFER=migration_database_transfer
SOVIEZ_MIG_OP_FILESTORE_TRANSFER=migration_filestore_transfer
SOVIEZ_MIG_OP_ADDON_TRANSFER=migration_addon_transfer
SOVIEZ_MIG_OP_CONFIG_TRANSFER=migration_config_transfer
SOVIEZ_MIG_OP_STAGE_TRANSFER=migration_stage_transfer
SOVIEZ_MIG_OP_FINAL_SYNC=migration_final_sync
SOVIEZ_MIG_OP_DESTINATION_VERIFY=migration_destination_verify
SOVIEZ_MIG_OP_TRANSFER_ABORT=migration_transfer_abort

SOVIEZ_MIG_PAIR_TTL_SECONDS="${SOVIEZ_MIG_PAIR_TTL_SECONDS:-86400}"
SOVIEZ_MIG_DNS_CHALLENGE_TTL_SECONDS="${SOVIEZ_MIG_DNS_CHALLENGE_TTL_SECONDS:-1800}"
SOVIEZ_MIG_ROUTING_PLAN_TTL_SECONDS="${SOVIEZ_MIG_ROUTING_PLAN_TTL_SECONDS:-86400}"
SOVIEZ_MIG_BOOTSTRAP_TTL_SECONDS="${SOVIEZ_MIG_BOOTSTRAP_TTL_SECONDS:-86400}"
SOVIEZ_MIG_DISCOVERY_TTL_SECONDS="${SOVIEZ_MIG_DISCOVERY_TTL_SECONDS:-86400}"
SOVIEZ_MIG_READINESS_TTL_SECONDS="${SOVIEZ_MIG_READINESS_TTL_SECONDS:-86400}"
SOVIEZ_MIG_CLOCK_SKEW_MAX_SECONDS="${SOVIEZ_MIG_CLOCK_SKEW_MAX_SECONDS:-300}"
SOVIEZ_MIG_CAPACITY_MARGIN_PCT="${SOVIEZ_MIG_CAPACITY_MARGIN_PCT:-25}"
SOVIEZ_MIG_BACKUP_MAX_AGE_SECONDS="${SOVIEZ_MIG_BACKUP_MAX_AGE_SECONDS:-86400}"
SOVIEZ_MIG_CHUNK_SIZE_BYTES="${SOVIEZ_MIG_CHUNK_SIZE_BYTES:-67108864}"
SOVIEZ_MIG_FREEZE_TIMEOUT_SECONDS="${SOVIEZ_MIG_FREEZE_TIMEOUT_SECONDS:-900}"
SOVIEZ_MIG_TRANSFER_PLAN_TTL_SECONDS="${SOVIEZ_MIG_TRANSFER_PLAN_TTL_SECONDS:-86400}"

SOVIEZ_MIGRATION_CODES=(
  MIGRATION_SOURCE_REQUIRED
  MIGRATION_SOURCE_INVALID
  MIGRATION_SOURCE_AMBIGUOUS
  MIGRATION_SOURCE_IDENTITY_MISMATCH
  MIGRATION_DESTINATION_REQUIRED
  MIGRATION_DESTINATION_INVALID
  MIGRATION_DESTINATION_UNSUPPORTED_OS
  MIGRATION_DESTINATION_UNSUPPORTED_ARCH
  MIGRATION_DESTINATION_CAPACITY_INSUFFICIENT
  MIGRATION_DESTINATION_INODES_INSUFFICIENT
  MIGRATION_DESTINATION_IDENTITY_MISMATCH
  MIGRATION_CLOCK_SKEW_BLOCKED
  MIGRATION_INSTALLER_REQUIRED
  MIGRATION_INSTALLER_SIGNATURE_INVALID
  MIGRATION_INSTALLER_DIGEST_MISMATCH
  MIGRATION_INSTALLER_ARCH_MISMATCH
  MIGRATION_INSTALLER_VERSION_INCOMPATIBLE
  MIGRATION_INSTALLER_EXPIRED
  MIGRATION_INSTALLER_UNTRUSTED_SIGNER
  MIGRATION_BOOTSTRAP_FAILED
  MIGRATION_BOOTSTRAP_EXPIRED
  MIGRATION_BOOTSTRAP_REVOKED
  MIGRATION_PAIR_REQUIRED
  MIGRATION_PAIR_EXPIRED
  MIGRATION_PAIR_SIGNATURE_INVALID
  MIGRATION_PAIR_REPLAY_DENIED
  MIGRATION_PAIR_IDENTITY_MISMATCH
  MIGRATION_PAIR_OWNER_CONFIRMATION_REQUIRED
  MIGRATION_PAIR_FINGERPRINT_MISMATCH
  MIGRATION_MTLS_FAILED
  MIGRATION_CONNECTIVITY_FAILED
  MIGRATION_COMPATIBILITY_WARNING
  MIGRATION_COMPATIBILITY_BLOCKED
  MIGRATION_BACKUP_WARNING
  MIGRATION_BACKUP_CAPABILITY_BLOCKED
  MIGRATION_TOKEN_REQUIRED_LATER
  MIGRATION_TOKEN_INELIGIBLE
  MIGRATION_TOKEN_NOT_CONSUMED
  MIGRATION_STAGE_NOT_SELECTABLE
  MIGRATION_STAGE_EXPIRED
  MIGRATION_ACTIVE_OPERATION_CONFLICT
  MIGRATION_READINESS_EXPIRED
  MIGRATION_READINESS_INPUT_CHANGED
  MIGRATION_ABORTED
  MIGRATION_RECOVERY_REQUIRED
  MIGRATION_DATA_TRANSFER_NOT_AUTHORIZED
  MIGRATION_DESTINATION_ACTIVATION_NOT_AUTHORIZED
  MIGRATION_DNS_CHANGE_NOT_AUTHORIZED
  MIGRATION_NOT_FOUND
  MIGRATION_CONFIRMATION_REQUIRED
  MIGRATION_PAIR_INVALID
  MIGRATION_PAIR_REVOKED
  MIGRATION_DOMAIN_REQUIRED
  MIGRATION_DOMAIN_INVALID
  MIGRATION_DOMAIN_OWNERSHIP_MISMATCH
  MIGRATION_DOMAIN_ALREADY_BOUND
  MIGRATION_DOMAIN_STRATEGY_REQUIRED
  MIGRATION_DNS_CHALLENGE_REQUIRED
  MIGRATION_DNS_CHALLENGE_EXPIRED
  MIGRATION_DNS_CHALLENGE_INVALID
  MIGRATION_DNS_CHALLENGE_REPLAY_DENIED
  MIGRATION_DNS_RECORD_NOT_FOUND
  MIGRATION_DNS_RECORD_MISMATCH
  MIGRATION_DNS_PROPAGATION_PENDING
  MIGRATION_DNS_AUTHORITATIVE_MISMATCH
  MIGRATION_DNSSEC_VALIDATION_FAILED
  MIGRATION_IPV4_UNREACHABLE
  MIGRATION_IPV6_UNREACHABLE
  MIGRATION_LANDING_PREPARE_FAILED
  MIGRATION_LANDING_HEALTH_FAILED
  MIGRATION_NGINX_CONFIG_INVALID
  MIGRATION_PORT_CONFLICT
  MIGRATION_CAA_BLOCKED
  MIGRATION_ACME_ORDER_FAILED
  MIGRATION_TLS_ISSUANCE_FAILED
  MIGRATION_TLS_CHAIN_INVALID
  MIGRATION_TLS_HOSTNAME_MISMATCH
  MIGRATION_TLS_KEY_STORAGE_FAILED
  MIGRATION_ROUTING_NOT_READY
  MIGRATION_SOURCE_ROUTING_CHANGED
  MIGRATION_SOURCE_DISRUPTION_DETECTED
  MIGRATION_DOMAIN_ABORTED
  MIGRATION_CUTOVER_NOT_AUTHORIZED
  MIGRATION_ROUTING_READINESS_REQUIRED
  MIGRATION_ROUTING_READINESS_EXPIRED
  MIGRATION_ROUTING_READINESS_INVALID
  MIGRATION_SOURCE_BACKUP_REQUIRED
  MIGRATION_SOURCE_BACKUP_TOO_OLD
  MIGRATION_SOURCE_BACKUP_NOT_VERIFIED
  MIGRATION_SOURCE_BACKUP_OWNERSHIP_MISMATCH
  MIGRATION_SOURCE_CAPACITY_INSUFFICIENT
  MIGRATION_TRANSFER_PLAN_REQUIRED
  MIGRATION_TRANSFER_PLAN_INVALID
  MIGRATION_TRANSFER_MANIFEST_REQUIRED
  MIGRATION_TRANSFER_MANIFEST_INVALID
  MIGRATION_TRANSFER_MANIFEST_EXPIRED
  MIGRATION_TRANSFER_CHANNEL_FAILED
  MIGRATION_TRANSFER_CERTIFICATE_INVALID
  MIGRATION_TRANSFER_REPLAY_DENIED
  MIGRATION_TRANSFER_CHUNK_INVALID
  MIGRATION_TRANSFER_CHUNK_CHECKSUM_MISMATCH
  MIGRATION_TRANSFER_CHUNK_OWNERSHIP_MISMATCH
  MIGRATION_TRANSFER_RESUME_MISMATCH
  MIGRATION_DATABASE_DUMP_FAILED
  MIGRATION_DATABASE_VERIFY_FAILED
  MIGRATION_DATABASE_TRANSFER_FAILED
  MIGRATION_DATABASE_RESTORE_FAILED
  MIGRATION_FILESTORE_PRESYNC_FAILED
  MIGRATION_FILESTORE_TRANSFER_FAILED
  MIGRATION_FILESTORE_RECONCILIATION_FAILED
  MIGRATION_ADDON_TRANSFER_FAILED
  MIGRATION_ADDON_SIGNATURE_INVALID
  MIGRATION_ADDON_NOT_APPROVED
  MIGRATION_CONFIG_TRANSFER_FAILED
  MIGRATION_SECRET_TRANSFER_NOT_AUTHORIZED
  MIGRATION_STAGE_NOT_SELECTED
  MIGRATION_STAGE_NOT_ELIGIBLE
  MIGRATION_STAGE_TRANSFER_FAILED
  MIGRATION_STAGE_OPTIONAL_FAILED
  MIGRATION_STAGE_MANDATORY_FAILED
  MIGRATION_SOURCE_FREEZE_REQUIRED
  MIGRATION_SOURCE_FREEZE_FAILED
  MIGRATION_SOURCE_FREEZE_TIMEOUT
  MIGRATION_SOURCE_FREEZE_RELEASE_FAILED
  MIGRATION_SOURCE_FREEZE_RECOVERY_REQUIRED
  MIGRATION_DESTINATION_STAGING_FAILED
  MIGRATION_DESTINATION_VALIDATION_FAILED
  MIGRATION_DESTINATION_PUBLIC_ROUTE_DETECTED
  MIGRATION_LICENSE_GUARD_STAGING_DENIED
  MIGRATION_TOKEN_NOT_RESERVED
  MIGRATION_TRANSFER_PAUSED
  MIGRATION_TRANSFER_ABORTED
  MIGRATION_TRANSFER_RECOVERY_REQUIRED
  MIGRATION_DESTINATION_CLEANUP_REQUIRED
  MIGRATION_TRANSFER_NOT_AUTHORIZED
  MIGRATION_BACKUP_GATE_FAILED
  MIGRATION_CAPACITY_BLOCKED
  MIGRATION_CHUNK_MISMATCH
  MIGRATION_RESUME_REQUIRED
  MIGRATION_STAGING_INVALID
  MIGRATION_PUBLIC_LOGIN_FORBIDDEN
  MIGRATION_SLOT_FORBIDDEN
  MIGRATION_ABORT_PRESERVED
  MIGRATION_READY_FOR_20_PASS
  MIGRATION_READY_FOR_20_WARNING
  MIGRATION_READY_FOR_20_BLOCKED
  MIGRATION_DATA_EGRESS_DENIED
)

soviez_migration_die() {
  local code="${1:-MIGRATION_RECOVERY_REQUIRED}" message="${2:-Migration preparation failed}"
  local ec="${SOVIEZ_ERR_MIGRATION:-25}"
  [[ -n "$ec" && "$ec" != "0" ]] || ec=25
  if declare -F soviez_log_error >/dev/null 2>&1; then
    soviez_log_error "migration:$code: $message"
  else
    echo "migration:$code: $message" >&2
  fi
  # Stable numeric exit: map to SOVIEZ_ERR_MIGRATION (never exit 0)
  exit "$ec"
}

soviez_migration_assert_no_transfer() {
  # Hard runtime guard — Phase 17/18 never authorize payload transfer or cutover
  if [[ "${SOVIEZ_MIG_ALLOW_TRANSFER:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_DATA_TRANSFER_NOT_AUTHORIZED "Phase 18 forbids data transfer"
  fi
  if [[ "${SOVIEZ_MIG_ALLOW_CUTOVER:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_CUTOVER_NOT_AUTHORIZED "Phase 18 forbids production cutover"
  fi
  return 0
}

soviez_migration_assert_no_cutover_or_token() {
  # Always blocks Phase 20+ mutations regardless of transfer authorization
  if [[ "${SOVIEZ_MIG_ALLOW_CUTOVER:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_CUTOVER_NOT_AUTHORIZED "Production cutover not authorized in Phase 19"
  fi
  if [[ "${SOVIEZ_MIG_ALLOW_ACTIVATION:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_DESTINATION_ACTIVATION_NOT_AUTHORIZED "Destination Production activation not authorized"
  fi
  if [[ "${SOVIEZ_MIG_ALLOW_TOKEN_RESERVE:-0}" == "1" || "${SOVIEZ_MIG_ALLOW_TOKEN_CONSUME:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_TOKEN_NOT_CONSUMED "Migration Token mutation not authorized in Phase 19"
  fi
  if [[ "${SOVIEZ_MIG_SAAS_PAYLOAD_RELAY:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_DATA_EGRESS_DENIED "SaaS payload relay forbidden"
  fi
  return 0
}

soviez_migration_assert_phase19_transfer_allowed() {
  # Phase 19 transfer ops only — requires exact pair + authorized op type
  local pair_id="${1:-}" op_type="${2:-}"
  [[ -n "$pair_id" ]] || soviez_migration_die MIGRATION_PAIR_REQUIRED "migration-pair ID required for transfer"
  [[ -n "$op_type" ]] || soviez_migration_die MIGRATION_TRANSFER_NOT_AUTHORIZED "transfer operation type required"
  case "$op_type" in
    migration_transfer_plan|migration_payload_presync|migration_database_transfer|migration_filestore_transfer|migration_addon_transfer|migration_config_transfer|migration_stage_transfer|migration_final_sync|migration_destination_verify|migration_transfer_abort)
      ;;
    *)
      soviez_migration_die MIGRATION_TRANSFER_NOT_AUTHORIZED "Unauthorized transfer op: $op_type"
      ;;
  esac
  soviez_migration_assert_no_cutover_or_token
  if [[ "${SOVIEZ_MIG_TOKEN_BURN:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_TOKEN_NOT_CONSUMED "Token burn forbidden"
  fi
  if [[ "${SOVIEZ_MIG_DNS_CUTOVER:-0}" == "1" ]]; then
    soviez_migration_die MIGRATION_CUTOVER_NOT_AUTHORIZED "DNS cutover forbidden"
  fi
  return 0
}
