# shellcheck shell=bash
# Phase 11 Stage denial / exit codes (stable protocol contracts).

SOVIEZ_ERR_STAGE=20

SOVIEZ_STAGE_DENIAL_CODES=(
  NO_MANAGED_PRODUCTION
  PRODUCTION_SELECTION_REQUIRED
  PRODUCTION_UNHEALTHY
  PRODUCTION_IDENTITY_MISMATCH
  LICENSE_BINDING_MISSING
  DEVICE_AUTH_REQUIRED
  DEVICE_REVOKED
  STAGE_ENTITLEMENT_REQUIRED
  STAGE_ENTITLEMENT_EXPIRED
  RESOURCE_ADMISSION_FAILED
  INSUFFICIENT_DISK
  INSUFFICIENT_MEMORY
  STAGE_ID_CONFLICT
  STAGE_DOMAIN_CONFLICT
  STAGE_DB_CONFLICT
  STAGE_CONTAINER_CONFLICT
  STAGE_MAC_CONFLICT
  OPERATION_AUTHORIZATION_FAILED
  TICKET_INVALID
  TICKET_EXPIRED
  TICKET_BINDING_MISMATCH
  TOOLING_UNAVAILABLE
  TOOLING_DIGEST_MISMATCH
  SNAPSHOT_FAILED
  DATABASE_RESTORE_FAILED
  FILESTORE_CLONE_FAILED
  STAGE_RUNTIME_FAILED
  NEUTRALIZATION_FAILED
  DNS_VALIDATION_FAILED
  SSL_ISSUANCE_FAILED
  ORIGIN_CERTIFICATE_FAILED
  REMOTE_COMPLETION_PENDING
  RECOVERY_REQUIRED
  DESTRUCTIVE_CONFIRMATION_REQUIRED
)

soviez_stage_die() {
  local denial="$1"
  shift || true
  soviez_log_error "STAGE_DENIAL=${denial} $*"
  # Prefer structured denial in stderr for non-TTY automation.
  printf '{"ok":false,"denial_code":"%s","message":"%s"}\n' "$denial" "$*" >&2
  exit "$SOVIEZ_ERR_STAGE"
}
