# shellcheck shell=bash
# Phase 13 — Stage retention structured codes (stable protocol).

SOVIEZ_ERR_RETENTION=21

SOVIEZ_RETENTION_DEFAULT_DAYS=14
SOVIEZ_RETENTION_MAXIMUM_DAYS=60
SOVIEZ_RETENTION_POLICY_VERSION="13.0.0"

# Authoritative host timezone for calendar-day display (installer policy).
# Timestamps persist in UTC; countdown uses this zone.
SOVIEZ_RETENTION_HOST_TZ="${SOVIEZ_RETENTION_HOST_TZ:-UTC}"

SOVIEZ_RETENTION_CODES=(
  STAGE_NOT_FOUND
  STAGE_IDENTITY_MISMATCH
  RETENTION_METADATA_MISSING
  RETENTION_METADATA_CORRUPT
  RETENTION_NOT_DUE
  RETENTION_DUE
  RETENTION_EXTENSION_AVAILABLE
  RETENTION_EXTENSION_LIMIT_REACHED
  RETENTION_EXTENSION_INVALID
  RETENTION_EXTENSION_REDUCES_DEADLINE
  RETENTION_MAXIMUM_EXCEEDED
  RETENTION_EXTENSION_TOO_LATE
  RETENTION_OPERATION_IN_PROGRESS
  RETENTION_WARNING_DUE
  RETENTION_DELETION_LOCKED
  FINAL_RETENTION_BACKUP_FAILED
  FINAL_RETENTION_BACKUP_INVALID
  SAFE_SHIELD_VALIDATION_FAILED
  STAGE_PRODUCTION_COLLISION
  STAGE_RESOURCE_OWNERSHIP_AMBIGUOUS
  STAGE_SHARED_RESOURCE_DETECTED
  STAGE_ACTIVE_OPERATION_CONFLICT
  RETENTION_DELETION_FAILED
  RETENTION_PARTIAL_DELETION
  RETENTION_RETRY_SCHEDULED
  RETENTION_RECOVERY_REQUIRED
  RETENTION_DELETED
  DESTRUCTIVE_CONFIRMATION_REQUIRED
  RETENTION_STAGE_DELETED
)

soviez_retention_die() {
  local code="$1"
  shift || true
  soviez_log_error "RETENTION_CODE=${code} $*"
  printf '{"ok":false,"code":"%s","message":"%s"}\n' "$code" "$*" >&2
  exit "$SOVIEZ_ERR_RETENTION"
}

soviez_retention_ok() {
  local code="$1"
  shift || true
  printf '{"ok":true,"code":"%s","message":"%s"}\n' "$code" "$*"
}
