# shellcheck shell=bash

SOVIEZ_ERR_UPDATE=23
SOVIEZ_UPDATE_SAFETY_WINDOW_HOURS="${SOVIEZ_UPDATE_SAFETY_WINDOW_HOURS:-24}"
SOVIEZ_UPDATE_OP_TYPE=production_update

soviez_utc_now() { date -u +%Y-%m-%dT%H:%M:%SZ; }
soviez_rand_hex() {
  local n="${1:-4}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$n" | head -c $((n * 2))
    return 0
  fi
  python3 -c "import secrets; print(secrets.token_hex(int('$n')))"
}

SOVIEZ_UPDATE_CODES=(
  UPDATE_TARGET_REQUIRED
  UPDATE_TARGET_INVALID
  UPDATE_TARGET_AMBIGUOUS
  UPDATE_STAGE_TARGET_DENIED
  UPDATE_PRODUCTION_IDENTITY_MISMATCH
  UPDATE_LICENSE_BINDING_MISMATCH
  UPDATE_DATABASE_UUID_MISMATCH
  UPDATE_HOST_IDENTITY_MISMATCH
  UPDATE_IDENTITY_MISMATCH
  UPDATE_CAPABILITY_REQUIRED
  UPDATE_CAPABILITY_EXPIRED
  UPDATE_MONTHLY_SUPPORT_DENIED
  UPDATE_UNBOUND_GRANT_DENIED
  UPDATE_WRONG_LICENSE
  UPDATE_WRONG_ACCOUNT
  UPDATE_GRANT_REVOKED
  UPDATE_OFFLINE_ENTITLEMENT_INVALID
  UPDATE_ENTITLEMENT_UNAVAILABLE
  UPDATE_RELEASE_NOT_FOUND
  UPDATE_RELEASE_UNSIGNED
  UPDATE_RELEASE_SIGNATURE_INVALID
  UPDATE_RELEASE_DIGEST_MISSING
  UPDATE_RELEASE_DIGEST_MISMATCH
  UPDATE_RELEASE_ARCH_MISMATCH
  UPDATE_RELEASE_INCOMPATIBLE
  UPDATE_RELEASE_DOWNGRADE_DENIED
  UPDATE_ALREADY_CURRENT
  UPDATE_PREFLIGHT_BLOCKED
  UPDATE_DISK_INSUFFICIENT
  UPDATE_INODES_INSUFFICIENT
  UPDATE_MEMORY_INSUFFICIENT
  UPDATE_BACKUP_CAPACITY_INSUFFICIENT
  UPDATE_WORKSPACE_CAPACITY_INSUFFICIENT
  UPDATE_BACKUP_FAILED
  UPDATE_BACKUP_INVALID
  UPDATE_BACKUP_INCONSISTENT
  UPDATE_ROLLBACK_SET_INCOMPLETE
  UPDATE_CANDIDATE_CREATE_FAILED
  UPDATE_CANDIDATE_UPGRADE_FAILED
  UPDATE_CANDIDATE_VALIDATION_FAILED
  UPDATE_LICENSE_VALIDATION_FAILED
  UPDATE_SWITCH_FAILED
  UPDATE_POST_SWITCH_VALIDATION_FAILED
  UPDATE_POST_VALIDATION_FAILED
  UPDATE_ROLLBACK_COMPLETED
  UPDATE_ROLLBACK_REQUIRED
  UPDATE_ROLLBACK_FAILED
  UPDATE_RECOVERY_REQUIRED
  UPDATE_CONFLICT
  UPDATE_CANCELLATION_NOT_SAFE
  UPDATE_OFFLINE_PACKAGE_INVALID
  DESTRUCTIVE_CONFIRMATION_REQUIRED
)

soviez_update_die() {
  local code="${1:-UPDATE_RECOVERY_REQUIRED}" message="${2:-Update failed}"
  soviez_log_error "${code}: ${message}"
  SOVIEZ_UPD_CODE="$code" SOVIEZ_UPD_MSG="$(soviez_redact_text "$message")" python3 - <<'PY' >&2
import json, os
print(json.dumps({"ok": False, "code": os.environ["SOVIEZ_UPD_CODE"],
                  "message": os.environ["SOVIEZ_UPD_MSG"]}, separators=(",", ":")))
PY
  exit "$SOVIEZ_ERR_UPDATE"
}

soviez_update_ok() {
  local code="${1:-OK}" message="${2:-OK}"
  SOVIEZ_UPD_CODE="$code" SOVIEZ_UPD_MSG="$(soviez_redact_text "$message")" python3 - <<'PY'
import json, os
print(json.dumps({"ok": True, "code": os.environ["SOVIEZ_UPD_CODE"],
                  "message": os.environ["SOVIEZ_UPD_MSG"]}, separators=(",", ":")))
PY
}
