# shellcheck shell=bash
# Phase 23 structured codes + die helper.

SOVIEZ_OFFLINE_BUNDLE_CODES=(
  OFFLINE_BUNDLE_REQUIRED
  OFFLINE_BUNDLE_NOT_FOUND
  OFFLINE_BUNDLE_FORMAT_INVALID
  OFFLINE_BUNDLE_SIGNATURE_INVALID
  OFFLINE_BUNDLE_MANIFEST_INVALID
  OFFLINE_BUNDLE_AUTHORIZATION_INVALID
  OFFLINE_BUNDLE_AUTHORIZATION_EXPIRED
  OFFLINE_BUNDLE_NOT_YET_VALID
  OFFLINE_BUNDLE_REVOKED
  OFFLINE_BUNDLE_REPLAY_DENIED
  OFFLINE_BUNDLE_ALREADY_APPLIED
  OFFLINE_BUNDLE_TARGET_MISMATCH
  OFFLINE_BUNDLE_LICENSE_MISMATCH
  OFFLINE_BUNDLE_DEVICE_MISMATCH
  OFFLINE_BUNDLE_ENVIRONMENT_MISMATCH
  OFFLINE_BUNDLE_CURRENT_VERSION_MISMATCH
  OFFLINE_BUNDLE_SOURCE_DIGEST_MISMATCH
  OFFLINE_BUNDLE_TARGET_DIGEST_MISMATCH
  OFFLINE_BUNDLE_ADDON_MANIFEST_MISMATCH
  OFFLINE_BUNDLE_ARCHITECTURE_MISMATCH
  OFFLINE_BUNDLE_OS_UNSUPPORTED
  OFFLINE_BUNDLE_POSTGRES_UNSUPPORTED
  OFFLINE_BUNDLE_INSUFFICIENT_DISK
  OFFLINE_BUNDLE_INSUFFICIENT_MEMORY
  OFFLINE_BUNDLE_BACKUP_REQUIRED
  OFFLINE_BUNDLE_BACKUP_FAILED
  OFFLINE_BUNDLE_PAYLOAD_CORRUPT
  OFFLINE_BUNDLE_IMAGE_IMPORT_FAILED
  OFFLINE_BUNDLE_ADDON_IMPORT_FAILED
  OFFLINE_BUNDLE_MIGRATION_FAILED
  OFFLINE_BUNDLE_CANDIDATE_BUILD_FAILED
  OFFLINE_BUNDLE_VALIDATION_FAILED
  OFFLINE_BUNDLE_SWITCH_FAILED
  OFFLINE_BUNDLE_ROLLBACK_REQUIRED
  OFFLINE_BUNDLE_ROLLBACK_FAILED
  OFFLINE_BUNDLE_CLOCK_ROLLBACK_DETECTED
  OFFLINE_BUNDLE_TRUST_ROOT_UNKNOWN
  OFFLINE_BUNDLE_TRUST_STATE_ROLLBACK
  OFFLINE_BUNDLE_KEY_REVOKED
  OFFLINE_BUNDLE_RESULT_EXPORT_FAILED
  OFFLINE_BUNDLE_RECONCILIATION_PENDING
  OFFLINE_BUNDLE_RECONCILIATION_CONFLICT
  OFFLINE_BUNDLE_REGISTRY_EXPORT_FAILED
  OFFLINE_BUNDLE_ARTIFACT_UPLOAD_FAILED
  OFFLINE_BUNDLE_CUSTOM_ADDON_UNSIGNED
  OFFLINE_BUNDLE_CUSTOM_ADDON_UNAPPROVED
  OFFLINE_UPDATE_ENTITLEMENT_REQUIRED
  OFFLINE_UPDATE_ENTITLEMENT_EXPIRED
  OFFLINE_UPDATE_ENTITLEMENT_REVOKED
  OFFLINE_UPDATE_PRODUCT_UPDATES_REQUIRED
  OFFLINE_UPDATE_OFFLINE_CAPABILITY_REQUIRED
  OFFLINE_UPDATE_CONFLICT
  OFFLINE_UPDATE_RECOVERY_REQUIRED
  OFFLINE_UPDATE_PHASE24_NOT_READY
  OFFLINE_PHASE23_CERT_GATE
)

soviez_offline_die() {
  local code="$1" msg="${2:-}"
  echo "[error] offline:${code}: ${msg}" >&2
  if [[ "${SOVIEZ_OFFLINE_SOFT_DIE:-0}" == "1" ]]; then
    return 25
  fi
  if declare -F soviez_die >/dev/null 2>&1; then
    soviez_die 25 "$code: $msg" 2>/dev/null || exit 25
  fi
  exit 25
}
