# shellcheck shell=bash

soviez_offline_bundle_paths_init() {
  soviez_paths_init 2>/dev/null || true
  SOVIEZ_OFFLINE_BUNDLE_ROOT="${SOVIEZ_OFFLINE_BUNDLE_ROOT:-$SOVIEZ_ROOT/offline_bundles}"
  SOVIEZ_OFFLINE_BUNDLE_IMPORT_DIR="${SOVIEZ_OFFLINE_BUNDLE_IMPORT_DIR:-$SOVIEZ_OFFLINE_BUNDLE_ROOT/import}"
  SOVIEZ_OFFLINE_BUNDLE_STAGING_DIR="${SOVIEZ_OFFLINE_BUNDLE_STAGING_DIR:-$SOVIEZ_OFFLINE_BUNDLE_ROOT/staging}"
  SOVIEZ_OFFLINE_BUNDLE_REPLAY_DB="${SOVIEZ_OFFLINE_BUNDLE_REPLAY_DB:-$SOVIEZ_OFFLINE_BUNDLE_ROOT/replay.json}"
  SOVIEZ_OFFLINE_BUNDLE_ISSUANCE_DIR="${SOVIEZ_OFFLINE_BUNDLE_ISSUANCE_DIR:-$SOVIEZ_OFFLINE_BUNDLE_ROOT/issuance}"
  SOVIEZ_OFFLINE_BUNDLE_OPS_DIR="${SOVIEZ_OFFLINE_BUNDLE_OPS_DIR:-$SOVIEZ_OFFLINE_BUNDLE_ROOT/ops}"
  mkdir -p "$SOVIEZ_OFFLINE_BUNDLE_IMPORT_DIR" "$SOVIEZ_OFFLINE_BUNDLE_STAGING_DIR" \
    "$SOVIEZ_OFFLINE_BUNDLE_ISSUANCE_DIR" "$SOVIEZ_OFFLINE_BUNDLE_OPS_DIR"
  export SOVIEZ_OFFLINE_BUNDLE_ROOT SOVIEZ_OFFLINE_BUNDLE_IMPORT_DIR \
    SOVIEZ_OFFLINE_BUNDLE_STAGING_DIR SOVIEZ_OFFLINE_BUNDLE_REPLAY_DB \
    SOVIEZ_OFFLINE_BUNDLE_ISSUANCE_DIR SOVIEZ_OFFLINE_BUNDLE_OPS_DIR
  if [[ ! -f "$SOVIEZ_OFFLINE_BUNDLE_REPLAY_DB" ]]; then
    printf '{"schema":"soviez.offline_bundle_replay.v1","entries":{}}\n' > "$SOVIEZ_OFFLINE_BUNDLE_REPLAY_DB"
  fi
}

soviez_offline_bundle_op_dir() {
  printf '%s/%s\n' "$SOVIEZ_OFFLINE_BUNDLE_OPS_DIR" "$1"
}
