# shellcheck shell=bash
# Phase 24 — security structured codes (reuse update/offline codes where equivalent).

SOVIEZ_ERR_SECURITY=24

soviez_security_die() {
  local code="$1" msg="${2:-}"
  echo "[error] security:${code}: ${msg}" >&2
  if declare -F soviez_die >/dev/null 2>&1; then
    soviez_die "${SOVIEZ_ERR_SECURITY:-24}" "$code" "$msg"
  fi
  exit "${SOVIEZ_ERR_SECURITY:-24}"
}

SOVIEZ_SECURITY_CODES=(
  SECURITY_SIGNATURE_REQUIRED
  SECURITY_SIGNATURE_INVALID
  SECURITY_SIGNER_UNKNOWN
  SECURITY_SIGNER_PURPOSE_MISMATCH
  SECURITY_SIGNER_REVOKED
  SECURITY_UNSIGNED_UPDATE_DENIED
  SECURITY_TEST_BYPASS_DENIED
  SECURITY_TICKET_REPLAY_DENIED
  SECURITY_TICKET_EXPIRED
  SECURITY_TICKET_TARGET_MISMATCH
  SECURITY_TICKET_PURPOSE_MISMATCH
  SECURITY_REGISTRY_SCOPE_DENIED
  SECURITY_REGISTRY_CREDENTIAL_PERSISTED
  SECURITY_REGISTRY_CREDENTIAL_LEAK
  SECURITY_PRIVATE_KEY_EXPOSED
  SECURITY_SERVICE_ROLE_EXPOSED
  SECURITY_SECRET_SCAN_FAILED
  SECURITY_DIST_SECRET_FOUND
  SECURITY_CROSS_TENANT_DENIED
  SECURITY_TRUST_STATE_ROLLBACK
  SECURITY_PHASE25_NOT_READY
  SECURITY_KEY_HYGIENE_REQUIRED
  SECURITY_FAKE_SIGNATURE_FORBIDDEN
  # Security Gate S1 — critical containment

  SEC_CRIT_PG_SUPERUSER
  SEC_CRIT_PG_CREATEROLE
  SEC_CRIT_PG_REPLICATION
  SEC_CRIT_PG_BYPASSRLS
  SEC_CRIT_PG_EXECUTE_SERVER_PROGRAM
  SEC_CRIT_PG_READ_SERVER_FILES
  SEC_CRIT_PG_WRITE_SERVER_FILES
  SEC_CRIT_PG_PUBLIC_PORT
  SEC_CRIT_ODOO_PUBLIC_PORT
  SEC_CRIT_PRIVILEGED_CONTAINER
  SEC_CRIT_DOCKER_SOCKET
  SEC_CRIT_HOST_NETWORK
  SEC_CRIT_WEAK_ADMIN_CREDENTIAL
  SEC_CRIT_PROXY_MODE_DISABLED
  SEC_CRIT_LIST_DB_ENABLED
  SEC_CRIT_SECURITY_STATE_UNKNOWN
  SEC_CRIT_BOOTSTRAP_SECRET_IN_ODOO
  SEC_CRIT_LEGACY_INSTALLER_UNSAFE
  SEC_HIGH_REVERSE_PROXY_UNREACHABLE
  SEC_HIGH_INTERNAL_DB_UNREACHABLE
  SEC_HIGH_OUTBOUND_NETWORK_BROKEN
  SEC_OK_CRITICAL_CONTAINMENT
  # Security Gate S2 — host & edge
  SEC_CRIT_FIREWALL_STATE_UNKNOWN
  SEC_CRIT_PUBLIC_ODOO_PORT
  SEC_CRIT_PUBLIC_POSTGRES_PORT
  SEC_CRIT_DOCKER_DAEMON_EXPOSED
  SEC_CRIT_NGINX_INVALID
  SEC_CRIT_TLS_REQUIRED_MISSING
  SEC_HIGH_DOCKER_FORWARDING_BROKEN
  SEC_HIGH_CONTAINER_DNS_BROKEN
  SEC_HIGH_REQUIRED_OUTBOUND_BROKEN
  SEC_HIGH_SSH_PASSWORD_AUTH_ENABLED
  SEC_HIGH_ROOT_SSH_ENABLED
  SEC_HIGH_WEBMIN_PUBLIC
  SEC_HIGH_LD_PRELOAD_UNEXPECTED
  SEC_WARN_SSH_HARDENING_DEFERRED
  SEC_WARN_WEBMIN_REVIEW_REQUIRED
  SEC_WARN_EDGE_CACHE_STALE
  SEC_OK_HOST_EDGE_HARDENED
  # Security Gate S3 — compromise detection
  SEC_CRIT_DB_COPY_PROGRAM
  SEC_CRIT_DB_REVERSE_SHELL
  SEC_CRIT_DB_KNOWN_MALWARE_IOC
  SEC_CRIT_HOST_ACTIVE_MINER
  SEC_CRIT_HOST_LD_PRELOAD_SUSPICIOUS
  SEC_HIGH_DB_OS_EXECUTION
  SEC_HIGH_DB_DOWNLOADER
  SEC_HIGH_DB_OBFUSCATED_EXEC
  SEC_HIGH_CUSTOM_ADDON_SHELL_EXEC
  SEC_HIGH_UNKNOWN_SUID_DRIFT
  SEC_HIGH_SYSTEMD_PERSISTENCE_DRIFT
  SEC_HIGH_CRON_PERSISTENCE_DRIFT
  SEC_HIGH_KNOWN_BAD_ENDPOINT
  SEC_WARN_TECHNICAL_RECORD_DRIFT
  SEC_WARN_UNKNOWN_REMOTE_ENDPOINT
  SEC_WARN_HOST_BASELINE_DRIFT
  SEC_INFO_TRUSTED_TECHNICAL_CHANGE
  SEC_OK_COMPROMISE_SCAN
  # Security Gate S4 — migration/restore quarantine
  SEC_CRIT_QUARANTINE_BYPASSED
  SEC_CRIT_PREBOOT_SCAN_FAILED
  SEC_CRIT_RESTORE_ARCHIVE_TRAVERSAL
  SEC_CRIT_RESTORE_SYMLINK_ESCAPE
  SEC_CRIT_QUARANTINE_EGRESS_OPEN
  SEC_CRIT_CRON_ACTIVE_IN_QUARANTINE
  SEC_CRIT_MAIL_ACTIVE_IN_QUARANTINE
  SEC_CRIT_DB_MALWARE_FINDING
  SEC_CRIT_PROMOTION_WITH_UNRESOLVED_CRITICAL
  SEC_HIGH_NO_TRUSTED_BASELINE
  SEC_HIGH_TECHNICAL_RECORD_REVIEW_REQUIRED
  SEC_HIGH_UNKNOWN_EXTERNAL_INTEGRATION
  SEC_WARN_FILESTORE_SUSPICIOUS_FILE
  SEC_WARN_REVIEW_REQUIRED
  SEC_OK_QUARANTINE_VALIDATED
  # Security Gate S5 — update, backup & network safety
  SEC_CRIT_POSTUPDATE_DB_UNREACHABLE
  SEC_CRIT_POSTUPDATE_ODOO_UNHEALTHY
  SEC_CRIT_POSTUPDATE_PROXY_UNREACHABLE
  SEC_CRIT_POSTUPDATE_PUBLIC_PORT_REGRESSION
  SEC_CRIT_POSTUPDATE_FIREWALL_REGRESSION
  SEC_HIGH_POSTUPDATE_DNS_BROKEN
  SEC_HIGH_POSTUPDATE_OUTBOUND_BROKEN
  SEC_HIGH_POSTUPDATE_PDF_BROKEN
  SEC_HIGH_DOCKER_RESTART_NETWORK_REGRESSION
  SEC_HIGH_FIREWALL_RELOAD_NETWORK_REGRESSION
  SEC_HIGH_BACKUP_LOCAL_ONLY
  SEC_CRIT_BACKUP_INTEGRITY_FAILED
  SEC_CRIT_RESTORE_TEST_FAILED
  SEC_HIGH_BACKUP_ENCRYPTION_MISSING
  SEC_HIGH_REBOOT_REQUIRED
  SEC_WARN_SERVICE_RESTART_REQUIRED
  SEC_WARN_IMMUTABLE_BACKUP_UNAVAILABLE
  SEC_OK_UPDATE_NETWORK_VALIDATED
  SEC_OK_BACKUP_VERIFIED
  SEC_OK_UPDATE_SAFETY
  SEC_OK_BACKUP_SAFETY
  SEC_CRIT_UPDATE_PRECHECK_FAILED
  SEC_HIGH_UPDATE_NEEDS_ACTION
  SEC_WARN_UPDATE_ROLLED_BACK
  # S5 Corrective Closure — package lock safety
  PKG_LOCK_WAITING
  PKG_LOCK_RELEASED
  PKG_LOCK_TIMEOUT
  PKG_LOCK_OWNER_UNKNOWN
  PKG_STATE_INCONSISTENT
  PKG_LOCK_UNSAFE_LEGACY_PATH_BLOCKED
)
