# shellcheck shell=bash

SOVIEZ_ERR_OPS=22
SOVIEZ_OPS_CODES=(
  OPERATION_NOT_FOUND
  OPERATION_IDENTITY_MISMATCH
  OPERATION_SCHEMA_UNSUPPORTED
  OPERATION_STATE_CORRUPT
  OPERATION_TRANSITION_INVALID
  OPERATION_ALREADY_RUNNING
  OPERATION_ALREADY_TERMINAL
  OPERATION_RESOURCE_CONFLICT
  OPERATION_LOCK_CONFLICT
  OPERATION_LOCK_STALE
  OPERATION_LOCK_RECOVERY_REQUIRED
  OPERATION_LOCK_IDENTITY_MISMATCH
  OPERATION_DEADLOCK_PREVENTED
  OPERATION_WORKER_MISSING
  OPERATION_WORKER_DUPLICATE
  OPERATION_WORKER_IDENTITY_MISMATCH
  OPERATION_HEARTBEAT_STALE
  OPERATION_SYSTEMD_UNIT_MISSING
  OPERATION_SYSTEMD_STATE_MISMATCH
  OPERATION_REATTACH_UNAVAILABLE
  OPERATION_CANCEL_ACCEPTED
  OPERATION_CANCEL_NOT_ALLOWED
  OPERATION_CANCEL_REQUIRES_CONFIRMATION
  OPERATION_CANCEL_ROLLBACK_STARTED
  OPERATION_CANCELLATION_TIMEOUT
  OPERATION_RETRY_NOT_ALLOWED
  OPERATION_RETRY_SCHEDULED
  OPERATION_RECOVERY_REQUIRED
  OPERATION_RECOVERY_NOT_SAFE
  OPERATION_MIGRATION_REQUIRED
  OPERATION_MIGRATION_FAILED
  OPERATION_LOG_UNAVAILABLE
  OPERATION_HISTORY_CORRUPT
  DESTRUCTIVE_CONFIRMATION_REQUIRED
  OPERATION_CONFIRMATION_REQUIRED
  OPERATION_CANONICAL_SYNC_FAILED
  OPERATION_CANONICAL_SYNC_PENDING
  OPERATION_CANONICAL_STATE_STALE
  OPERATION_CANONICAL_REVISION_MISMATCH
  OPERATION_REGISTRY_SYNC_FAILED
  OPERATION_EVENT_SYNC_FAILED
  OPERATION_TERMINAL_SYNC_INCOMPLETE
  OPERATION_SYNC_RECONCILED
  OPERATION_SYNC_RECOVERY_REQUIRED
)

soviez_ops_die() {
  local code="${1:-OPERATION_STATE_CORRUPT}" message="${2:-Operation failed}"
  soviez_log_error "${code}: ${message}"
  SOVIEZ_OPS_CODE="$code" SOVIEZ_OPS_MESSAGE="$(soviez_redact_text "$message")" python3 - <<'PY' >&2
import json, os
print(json.dumps({"ok": False, "code": os.environ["SOVIEZ_OPS_CODE"],
                  "message": os.environ["SOVIEZ_OPS_MESSAGE"]}, separators=(",", ":")))
PY
  exit "$SOVIEZ_ERR_OPS"
}

soviez_ops_ok() {
  local code="${1:-OK}" message="${2:-OK}"
  SOVIEZ_OPS_CODE="$code" SOVIEZ_OPS_MESSAGE="$(soviez_redact_text "$message")" python3 - <<'PY'
import json, os
print(json.dumps({"ok": True, "code": os.environ["SOVIEZ_OPS_CODE"],
                  "message": os.environ["SOVIEZ_OPS_MESSAGE"]}, separators=(",", ":")))
PY
}
